insert into Specialty (field) values ('Allergy');
insert into Specialty (field) values ('Cardiology');
insert into Specialty (field) values ('Chiropractic');
insert into Specialty (field) values ('Dermatology');
insert into Specialty (field) values ('Dentistry');
insert into Specialty (field) values ('ENT');
insert into Specialty (field) values ('Endocrinology');
insert into Specialty (field) values ('Gastroenterology');
insert into Specialty (field) values ('Orthopedics');
insert into Specialty (field) values ('Pain Management');
insert into Specialty (field) values ('Pediatrics');
insert into Specialty (field) values ('Physical Therapy');
insert into Specialty (field) values ('Psychiatry');
insert into Specialty (field) values ('Rheumatology');
insert into Specialty (field) values ('Urology');

insert into Practitioner (last_name, first_name,specialty_id) values ('Abernathy', 'Katherine', 1);
insert into Practitioner (last_name, first_name,specialty_id) values ('Clayton', 'Michael', 1);
insert into Practitioner (last_name, first_name,specialty_id) values ('Clayton', 'Michael', 1);
insert into Practitioner (last_name, first_name,specialty_id) values ('Feldman', 'Bruce', 1);
insert into Practitioner (last_name, first_name,specialty_id) values ('Honsinger', 'Richard', 1);
insert into Practitioner (last_name, first_name,specialty_id) values ('Jenkins', 'Teresa', 1);
insert into Practitioner (last_name, first_name,specialty_id) values ('Keslin', 'Michael', 1);
insert into Practitioner (last_name, first_name,specialty_id) values ('Rosandich', 'Ronald', 1);
insert into Practitioner (last_name, first_name,specialty_id) values ('Tolber', 'Steven', 1);


insert into Practitioner (last_name, first_name,specialty_id) values ('Achrekar', 'Abinash', 2);
insert into Practitioner (last_name, first_name,specialty_id) values ('Alkouz', 'Munif', 2);
insert into Practitioner (last_name, first_name,specialty_id) values ('Allen', 'Kathleen', 2);
insert into Practitioner (last_name, first_name,specialty_id) values ('Bendersky', 'Ruby', 2);
insert into Practitioner (last_name, first_name,specialty_id) values ('Cavanaugh', 'Brendan', 2);
insert into Practitioner (last_name, first_name,specialty_id) values ('Chen', 'Jay', 2);
insert into Practitioner (last_name, first_name,specialty_id) values ('Gavaldon', 'Christopher', 2);
insert into Practitioner (last_name, first_name,specialty_id) values ('Lopez', 'Erica', 2);
insert into Practitioner (last_name, first_name,specialty_id) values ('Marin', 'Vanessa', 2);
insert into Practitioner (last_name, first_name,specialty_id) values ('Ramo', 'Barry', 2);
insert into Practitioner (last_name, first_name,specialty_id) values ('Voyles', 'Wyatt', 2);

insert into Practitioner (last_name, first_name,specialty_id) values ('Bateman', 'Tim', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Berlin', 'John', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Blessing', 'Lindsey', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Blair', 'Emily', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Blair', 'Randy', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Cecil', 'Christopher', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Coogan', 'Kelly', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Dehoogh', 'Austin', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Del Angel', 'Tony', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Emberger', 'Michelle', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Freeburg', 'Thomas', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Gardner', 'Stephen', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Hightower', 'Beau', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Lovin', 'Bill', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Manson', 'Kirk', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Marcus', 'Rion', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Ramirez', 'Ruben', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Valenti', 'Helene', 3);
insert into Practitioner (last_name, first_name,specialty_id) values ('Vawter', 'John', 3);

insert into Practitioner (last_name, first_name,specialty_id) values ('Bang', 'Ran', 4);
insert into Practitioner (last_name, first_name,specialty_id) values ('Berry', 'Tamara', 4);
insert into Practitioner (last_name, first_name,specialty_id) values ('Carey', 'John', 4);
insert into Practitioner (last_name, first_name,specialty_id) values ('Einhorn', 'Barbara', 4);
insert into Practitioner (last_name, first_name,specialty_id) values ('Glass', 'Leslie', 4);
insert into Practitioner (last_name, first_name,specialty_id) values ('Nguyen', 'Tien', 4);
insert into Practitioner (last_name, first_name,specialty_id) values ('Purcell', 'Carol', 4);
insert into Practitioner (last_name, first_name,specialty_id) values ('Unalivia', 'Amanda', 4);
insert into Practitioner (last_name, first_name,specialty_id) values ('Wicks', 'Dane', 4);

insert into Practitioner (last_name, first_name,specialty_id) values ('Allan', 'Grant', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Anderson', 'Steven', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Chodosh', 'David', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Gomez', 'Terry', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Haight', 'Michael', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Henry', 'Kyle', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Jaime', 'Lillian', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Ku', 'James', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Lee', 'Monique', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Lines', 'Derek', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('LoPour', 'Greg', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Newsome', 'Boyd', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Onuora', 'Obiajulu', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Rogers', 'Jacob', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Sanchez', 'Gary', 5);
insert into Practitioner (last_name, first_name,specialty_id) values ('Sanchez', 'Greg', 5);

insert into Practitioner (last_name, first_name,specialty_id) values ('Beauchamp', 'Mark', 6);
insert into Practitioner (last_name, first_name,specialty_id) values ('Escudero', 'Ronald', 6);
insert into Practitioner (last_name, first_name,specialty_id) values ('Nuara', 'Michael', 6);
insert into Practitioner (last_name, first_name,specialty_id) values ('Olson', 'Garth', 6);
insert into Practitioner (last_name, first_name,specialty_id) values ('Pena', 'Blanca', 6);
insert into Practitioner (last_name, first_name,specialty_id) values ('Ribner', 'Andrew', 6);
insert into Practitioner (last_name, first_name,specialty_id) values ('Shama', 'Liat', 6);
insert into Practitioner (last_name, first_name,specialty_id) values ('Simpson', 'John', 6);
insert into Practitioner (last_name, first_name,specialty_id) values ('Spafford', 'Michael', 6);

insert into Practitioner (last_name, first_name,specialty_id) values ('Abernathy', 'Katherine', 7);
insert into Practitioner (last_name, first_name,specialty_id) values ('Clayton', 'Michael', 7);
insert into Practitioner (last_name, first_name,specialty_id) values ('Clayton', 'Michael', 7);
insert into Practitioner (last_name, first_name,specialty_id) values ('Feldman', 'Bruce', 7);
insert into Practitioner (last_name, first_name,specialty_id) values ('Honsinger', 'Richard', 7);
insert into Practitioner (last_name, first_name,specialty_id) values ('Jenkins', 'Teresa', 7);
insert into Practitioner (last_name, first_name,specialty_id) values ('Keslin', 'Michael', 7);
insert into Practitioner (last_name, first_name,specialty_id) values ('Rosandich', 'Ronald', 7);
insert into Practitioner (last_name, first_name,specialty_id) values ('Tolber', 'Steven', 7);

insert into Practitioner (last_name, first_name,specialty_id) values ('Allen', 'Deborah', 8);
insert into Practitioner (last_name, first_name,specialty_id) values ('Beck', 'Nancy', 8);
insert into Practitioner (last_name, first_name,specialty_id) values ('Byreddi', 'Deepthi', 8);
insert into Practitioner (last_name, first_name,specialty_id) values ('Pinon', 'Ivan', 8);
insert into Practitioner (last_name, first_name,specialty_id) values ('Reyes', 'May', 8);
insert into Practitioner (last_name, first_name,specialty_id) values ('Terlecki', 'Marta', 8);
insert into Practitioner (last_name, first_name,specialty_id) values ('Truong', 'Phuong', 8);
insert into Practitioner (last_name, first_name,specialty_id) values ('Wittenberg', 'Rebecca', 8);
insert into Practitioner (last_name, first_name,specialty_id) values ('Zerah', 'Michele', 8);

insert into Practitioner (last_name, first_name,specialty_id) values ('Adams', 'Gabrielle', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Adnan', 'Mohammed', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Barakat', 'Jehad', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Chang', 'Christopher', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Chua', 'Eduardo', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Farrer', 'Julie', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Gavin', 'Michael', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Gogel', 'Howard', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Kaza', 'Archana', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Martinez', 'James', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Qaseem', 'Tahir', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Riley', 'Thomas', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Saad', 'Abdo', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Taylor', 'Lance', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Valenzuela', 'Gregg', 9);
insert into Practitioner (last_name, first_name,specialty_id) values ('Villas-Adams', 'Angelina', 9);

insert into Practitioner (last_name, first_name,specialty_id) values ('Altman', 'Alan', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Atler', 'Edward', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Bernstein', 'David', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Chavez', 'Gary', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Dennis', 'Deborah', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Evans', 'Scott', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Franco', 'John', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Gehlert', 'Rick', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Hoekstra', 'Dale', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Legant', 'Paul', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Lilley', 'Matthew', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Orr', 'Charlotte', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Showalter', 'Dean', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Veitch', 'Andrew', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Wasserburger', 'Jory', 10);
insert into Practitioner (last_name, first_name,specialty_id) values ('Yelverton', 'William', 10);

insert into Practitioner (last_name, first_name,specialty_id) values ('Bridges', 'Jerry', 11);
insert into Practitioner (last_name, first_name,specialty_id) values ('Carmany', 'Emily', 11);
insert into Practitioner (last_name, first_name,specialty_id) values ('Katzman', 'Joanna', 11);
insert into Practitioner (last_name, first_name,specialty_id) values ('Malizzo', 'Michael', 11);
insert into Practitioner (last_name, first_name,specialty_id) values ('Palacio', 'Michael', 11);
insert into Practitioner (last_name, first_name,specialty_id) values ('Poon', 'Edward', 11);
insert into Practitioner (last_name, first_name,specialty_id) values ('Schoenberger', 'Kyle', 11);
insert into Practitioner (last_name, first_name,specialty_id) values ('Woodruff', 'Marchell', 11);
insert into Practitioner (last_name, first_name,specialty_id) values ('Zuniga', 'Robert', 11);

insert into Practitioner (last_name, first_name,specialty_id) values ('Agarwal', 'Hemant', 12);
insert into Practitioner (last_name, first_name,specialty_id) values ('Coleman', 'Denise', 12);
insert into Practitioner (last_name, first_name,specialty_id) values ('Crowley', 'Mark', 12);
insert into Practitioner (last_name, first_name,specialty_id) values ('Hadid', 'Senan', 12);
insert into Practitioner (last_name, first_name,specialty_id) values ('Subbaswamy', 'Anjali', 12);

insert into Practitioner (last_name, first_name,specialty_id) values ('Black', 'Pamela', 13);
insert into Practitioner (last_name, first_name,specialty_id) values ('Eaton-Walker', 'Angela', 13);
insert into Practitioner (last_name, first_name,specialty_id) values ('Esparza', 'Carlos', 13);
insert into Practitioner (last_name, first_name,specialty_id) values ('Knaus', 'Evan', 13);
insert into Practitioner (last_name, first_name,specialty_id) values ('Mallory', 'Harvey', 13);
insert into Practitioner (last_name, first_name,specialty_id) values ('Manole', 'Athanasios', 13);
insert into Practitioner (last_name, first_name,specialty_id) values ('Ross', 'Barrie', 13);
insert into Practitioner (last_name, first_name,specialty_id) values ('Taylor', 'Denise', 13);
insert into Practitioner (last_name, first_name,specialty_id) values ('Wallach', 'Robert', 13);

insert into Practitioner (last_name, first_name,specialty_id) values ('Arnet', 'Neil', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Bakhtiar', 'Parvaneh', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Byreddi', 'Deepthi', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Gee', 'Debbie', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Graff', 'Adam', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Holzgang', 'Anthony', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Jaccard', 'Debra', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Rednick', 'Leah', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Schiess', 'Nancy', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Sievert', 'Michael', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Thaler', 'Gail', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Umpierre', 'Anthony', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Velasquez', 'Eva', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Vera', 'Javier', 14);
insert into Practitioner (last_name, first_name,specialty_id) values ('Weil', 'Elizabeth', 14);

insert into Practitioner (last_name, first_name,specialty_id) values ('Annem', 'Chandrahasa', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Bankhurst', 'Arthur', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Cook', 'Gladys', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Dean', 'Jacqueline', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Emil', 'Nicole', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Fields', 'Roderick', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Garcia', 'Salvador', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Konstantinov', 'Konstantin', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Norton', 'Hillary', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Peisajovich', 'Andres', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Reiter', 'Kimberly', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Rosandich', 'Peter', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Stermer', 'Clifford', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Stoerner', 'Scott', 15);
insert into Practitioner (last_name, first_name,specialty_id) values ('Uribe', 'Jorge', 15);